services:
  db:
    image: mydb

    volumes:
      - vol:/var/lib/mysql 
  
    ports:
      - "3306:3306"
  

  backend:
    image: backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    
    image: frontend  

    ports:
      - "4200:4200"  

    depends_on:
      - backend
   
   

volumes:
  vol:
    external: true